apiVersion: v1
kind: Service 
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort # ClusterIP, # NodePort, # LoadBalancer, # ExternalName
  selector:
    app: nginx-webapp
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 30080 # NodePort (Optional)(Node Port Range: 30000-32768)